version: 5.1.0
variant: default
# logo: /img/logo.svg
logo: 
    text: sultan
head:
    favicon: /img/favicon.svg
    manifest:
        name: 
        short_name: 
        start_url: 
        theme_color: 
        background_color: 
        display: standalone
        icons:
            -
                src: ''
                sizes: ''
                type: 
    open_graph:
        title: 
        type: blog
        url: 
        image: 
        site_name: 
        author: 
        description: 
        twitter_card: 
        twitter_id: 
        twitter_site: 
        google_plus: 
        fb_admins: 
        fb_app_id: 
    structured_data:
        title: 
        description: 
        url: 
        author: 
        publisher: 
        publisher_logo: 
        image: 
    meta:
        - ''
    rss: 
navbar:
    menu:
        主页: /
        文章: /archives
        # 留言: /message
        思绪: /thought
        关于我: /about
    links:
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/sultan-young
footer:
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/sultan-young
article:
    highlight:
        theme: atom-one-light
        clipboard: true
        fold: unfolded
    readtime: true
    update_time: true
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Noncommercial:
            icon: fab fa-creative-commons-nc
            url: https://creativecommons.org/licenses/by-nc/4.0/
search:
    type: insight
    index_pages: true
comment:
        type: utterances
        repo: sultan-young/talk
        issue_term: pathname        # 必填项，与issue_number二选一填写
        # issue_number: 1           # 必填项，与issue_term二选一填写，每篇文章对应一个issue，填写前需要手动创建issue
        label: some-issue-label     # 可选填
        theme: github-light  
# donates:
#     -
#         type: afdian
#         url: ''
#     -
#         type: alipay
#         qrcode: ''
#     -
#         type: buymeacoffee
#         url: ''
#     -
#         type: patreon
#         url: ''
#     -
#         type: paypal
#         business: ''
#         currency_code: USD
#     -
#         type: wechat
#         qrcode: ''
# share:
#     type: sharethis
#     install_url: ''
sidebar:
    left:
        sticky: false
    right:
        sticky: true
widgets:
    -
        position: right
        type: profile
        author: sultan
        author_title: 前端开发者
        location: 浙江 杭州
        avatar: 
        avatar_rounded: false
        gravatar: 
        follow_link: https://github.com/sultan-young
        social_links:
            Github:
                icon: fab fa-github
                url: https://github.com/sultan-young
            掘金: https://juejin.cn/user/2709653869308030/posts
            知乎: https://www.zhihu.com/people/yang1050462990
            CSDN: https://blog.csdn.net/qq_36205941
    -
        position: right
        type: toc
        index: true
    -
        position: left
        type: recent_posts
    -
        position: left
        type: categories
    -
        position: left
        type: archives
    -
        position: left
        type: tags
        order_by: name
        amount: 
        show_count: true
    -
        position: left
        type: links
        # 友站名称与链接
        links:
            Hexo: 'https://hexo.io'
            Bulma: 'https://bulma.io'
    # -
    #     position: left
    #     type: subscribe_email
    #     description: 
    #     feedburner_id: ''
    # -
    #     position: left
    #     type: adsense
    #     client_id: ''
    #     slot_id: ''
    # -
    #     position: left
    #     type: followit
    #     description: 
    #     action_url: ''
    #     verification_code: ''
plugins:
    animejs: true
    back_to_top: true
    baidu_analytics:
        tracking_id: 
    bing_webmaster:
        tracking_id: 
    busuanzi: false
    cnzz:
        id: 
        web_id: 
    cookie_consent:
        type: info
        theme: edgeless
        static: false
        position: bottom-left
        policyLink: https://www.cookiesandyou.com/
    gallery: true
    google_analytics:
        tracking_id: 
    hotjar:
        site_id: 
    katex: false
    mathjax: false
    outdated_browser: false
    progressbar: true
    statcounter:
        project: 
        security: 
    twitter_conversion_tracking:
        pixel_id: 
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: fontawesome
